export interface FieldMetadata {
  name: string;
  uiLabel: string;
  section: string;
  dataType: "string" | "number" | "boolean" | "date" | "enum" | "array-string" | "time";
  required: boolean;
  repeatable: boolean;
  allowedValues?: string[];
  placeholder?: string;
  helpText?: string;
  validationRules?: string;
  normalizationRules?: string;
  databaseField: string;
  databaseTable: string;
  fhirResource?: string;
  fhirPath?: string;
  fhirDatatype?: string;
  systemUrl?: string;
  searchable: boolean;
  patientVisible: boolean;
  adminOnly: boolean;
  sensitive: boolean;
}

export const DOCTOR_ONBOARDING_FIELDS: FieldMetadata[] = [
  // SECTION 1: Identity
  {
    name: "title",
    uiLabel: "Title",
    section: "Identity",
    dataType: "enum",
    required: true,
    repeatable: false,
    allowedValues: ["Dr.", "Prof.", "Assoc. Prof.", "Asst. Prof."],
    placeholder: "Select Title...",
    helpText: "Select your official professional title.",
    validationRules: "Must be one of the pre-selected allowed values.",
    normalizationRules: "Trim whitespace.",
    databaseField: "title",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.name.prefix",
    fhirDatatype: "string",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "firstName",
    uiLabel: "First Name",
    section: "Identity",
    dataType: "string",
    required: true,
    repeatable: false,
    placeholder: "Enter first name",
    helpText: "Enter your first name as listed on your medical registry document.",
    validationRules: "String length between 1 and 100 characters. No special characters except hyphens and apostrophes.",
    normalizationRules: "Trim whitespace. Titlecase capitalization.",
    databaseField: "firstName",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.name.given[0]",
    fhirDatatype: "string",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "middleName",
    uiLabel: "Middle Name",
    section: "Identity",
    dataType: "string",
    required: false,
    repeatable: false,
    placeholder: "Enter middle name",
    helpText: "Enter your middle name if applicable.",
    validationRules: "String length between 1 and 100 characters.",
    normalizationRules: "Trim whitespace. Titlecase capitalization.",
    databaseField: "middleName",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.name.given[1]",
    fhirDatatype: "string",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "lastName",
    uiLabel: "Last Name",
    section: "Identity",
    dataType: "string",
    required: true,
    repeatable: false,
    placeholder: "Enter last name",
    helpText: "Enter your last name or family name as listed on your medical registry document.",
    validationRules: "String length between 1 and 100 characters.",
    normalizationRules: "Trim whitespace. Titlecase capitalization.",
    databaseField: "lastName",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.name.family",
    fhirDatatype: "string",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "displayName",
    uiLabel: "Display Name",
    section: "Identity",
    dataType: "string",
    required: true,
    repeatable: false,
    placeholder: "e.g., Dr. Alexis Carter",
    helpText: "This is the name patients will see on the platform (typically 'Dr. [First Name] [Last Name]').",
    validationRules: "String length between 2 and 150 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "displayName",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.name.text",
    fhirDatatype: "string",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "gender",
    uiLabel: "Gender",
    section: "Identity",
    dataType: "enum",
    required: true,
    repeatable: false,
    allowedValues: ["male", "female", "other", "unknown"],
    placeholder: "Select gender",
    helpText: "Select your gender.",
    validationRules: "Must be one of: 'male', 'female', 'other', 'unknown'.",
    normalizationRules: "Lowercase.",
    databaseField: "gender",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.gender",
    fhirDatatype: "code",
    systemUrl: "http://hl7.org/fhir/valueset/administrative-gender",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: true
  },
  {
    name: "dateOfBirth",
    uiLabel: "Date of Birth",
    section: "Identity",
    dataType: "date",
    required: true,
    repeatable: false,
    placeholder: "YYYY-MM-DD",
    helpText: "Enter your date of birth.",
    validationRules: "Must be a valid date. Practitioner must be at least 18 years old. Cannot be in the future.",
    normalizationRules: "Date object conversion to ISO string.",
    databaseField: "birthDate",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.birthDate",
    fhirDatatype: "date",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: true
  },
  {
    name: "profilePhoto",
    uiLabel: "Profile Photo",
    section: "Identity",
    dataType: "string",
    required: false,
    repeatable: false,
    placeholder: "Upload photo",
    helpText: "Upload a professional headshot. JPEG or PNG, max 5MB.",
    validationRules: "Must be a valid URL string matching PNG, JPG, or JPEG extension.",
    normalizationRules: "Trim whitespace.",
    databaseField: "profilePhoto",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.photo",
    fhirDatatype: "Attachment",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 2: Contact
  {
    name: "mobile",
    uiLabel: "Mobile Number",
    section: "Contact",
    dataType: "string",
    required: true,
    repeatable: false,
    placeholder: "+1-555-555-5555",
    helpText: "Enter your primary contact phone number.",
    validationRules: "Must match phone number format (regex: ^\\+?[1-9]\\d{1,14}$).",
    normalizationRules: "Strip spaces, hyphens, and ensure E.164 prefix formatting.",
    databaseField: "phone",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.telecom[system=phone, use=mobile].value",
    fhirDatatype: "ContactPoint",
    searchable: true,
    patientVisible: false,
    adminOnly: false,
    sensitive: true
  },
  {
    name: "email",
    uiLabel: "Email Address",
    section: "Contact",
    dataType: "string",
    required: true,
    repeatable: false,
    placeholder: "doctor@drgodly.com",
    helpText: "Enter your professional email address.",
    validationRules: "Must conform to email validation standards.",
    normalizationRules: "Trim whitespace, convert to lowercase.",
    databaseField: "email",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.telecom[system=email, use=work].value",
    fhirDatatype: "ContactPoint",
    searchable: true,
    patientVisible: false,
    adminOnly: false,
    sensitive: true
  },
  {
    name: "alternatePhone",
    uiLabel: "Alternate Phone",
    section: "Contact",
    dataType: "string",
    required: false,
    repeatable: false,
    placeholder: "+1-555-555-5556",
    helpText: "Enter an alternate phone number for emergency or backup contact.",
    validationRules: "Must match phone number format if provided.",
    normalizationRules: "E.164 normalisation.",
    databaseField: "alternatePhone",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.telecom[system=phone, use=work].value",
    fhirDatatype: "ContactPoint",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: true
  },
  {
    name: "preferredContactMethod",
    uiLabel: "Preferred Contact Method",
    section: "Contact",
    dataType: "enum",
    required: true,
    repeatable: false,
    allowedValues: ["email", "phone", "sms"],
    placeholder: "Select preference",
    helpText: "How would you prefer to receive notifications?",
    validationRules: "Must be one of: 'email', 'phone', 'sms'.",
    normalizationRules: "Lowercase.",
    databaseField: "preferredContactMethod",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.telecom.extension[url='http://drgodly.com/fhir/StructureDefinition/preferred-contact']",
    fhirDatatype: "code",
    systemUrl: "http://drgodly.com/fhir/StructureDefinition/preferred-contact",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 3: Medical Registration
  {
    name: "medicalSystem",
    uiLabel: "Medical System",
    section: "Medical Registration",
    dataType: "string",
    required: true,
    repeatable: false,
    allowedValues: ["Allopathy", "Homeopathy", "Ayurveda", "Unani", "Siddha"],
    placeholder: "Select Medical System",
    helpText: "Choose the medicine system you practice.",
    validationRules: "Must be one of the specified allowed values.",
    normalizationRules: "Capitalization.",
    databaseField: "medicalSystem",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.code.coding[system='http://drgodly.com/fhir/CodeSystem/medical-system'].code",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://drgodly.com/fhir/CodeSystem/medical-system",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "registrationAuthority",
    uiLabel: "Registration Authority",
    section: "Medical Registration",
    dataType: "string",
    required: true,
    repeatable: false,
    placeholder: "e.g., Medical Council of India, State Medical Board",
    helpText: "The licensing authority that issued your registration.",
    validationRules: "Minimum 2 characters, maximum 150 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "registrationAuthority",
    databaseTable: "PractitionerIdentifier",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.identifier.assigner.display",
    fhirDatatype: "Reference",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "stateMedicalCouncil",
    uiLabel: "State Medical Council",
    section: "Medical Registration",
    dataType: "string",
    required: false,
    repeatable: false,
    placeholder: "e.g., Karnataka Medical Council",
    helpText: "The state medical council where registered (if applicable, e.g. for India).",
    validationRules: "String length under 150 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "stateMedicalCouncil",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.issuer.display",
    fhirDatatype: "Reference",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "registrationNumber",
    uiLabel: "Medical Registration Number",
    section: "Medical Registration",
    dataType: "string",
    required: true,
    repeatable: false,
    placeholder: "e.g., KMC-12345",
    helpText: "Your official medical license or registration registry number.",
    validationRules: "String length between 2 and 50 characters. Must be unique.",
    normalizationRules: "Trim whitespace, uppercase letters.",
    databaseField: "value",
    databaseTable: "PractitionerIdentifier",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.identifier[type=license].value",
    fhirDatatype: "Identifier",
    systemUrl: "http://terminology.hl7.org/CodeSystem/v2-0203",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "registrationDate",
    uiLabel: "Registration Date",
    section: "Medical Registration",
    dataType: "date",
    required: true,
    repeatable: false,
    placeholder: "YYYY-MM-DD",
    helpText: "Date when your registration was first issued.",
    validationRules: "Valid date. Cannot be in the future.",
    normalizationRules: "Date object serialization.",
    databaseField: "registrationDate",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.period.start",
    fhirDatatype: "Period",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "registrationExpiryDate",
    uiLabel: "Registration Expiry Date",
    section: "Medical Registration",
    dataType: "date",
    required: true,
    repeatable: false,
    placeholder: "YYYY-MM-DD",
    helpText: "Expiry date of your current medical license.",
    validationRules: "Must be after registrationDate. Must be in the future for submission.",
    normalizationRules: "Date object.",
    databaseField: "registrationExpiryDate",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.period.end",
    fhirDatatype: "Period",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "registrationStatus",
    uiLabel: "Registration Status",
    section: "Medical Registration",
    dataType: "enum",
    required: true,
    repeatable: false,
    allowedValues: ["active", "expired", "suspended"],
    placeholder: "Select status",
    helpText: "The current state of your license with the authority.",
    validationRules: "Must be one of the allowed statuses.",
    normalizationRules: "Lowercase.",
    databaseField: "registrationStatus",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.extension[url='http://hl7.org/fhir/StructureDefinition/qualification-status']",
    fhirDatatype: "code",
    systemUrl: "http://hl7.org/fhir/StructureDefinition/qualification-status",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "imrNumber",
    uiLabel: "Indian Medical Register (IMR) Number",
    section: "Medical Registration",
    dataType: "string",
    required: false,
    repeatable: false,
    placeholder: "e.g., IMR-99887",
    helpText: "Your IMR ID (mandatory for practicing Allopathic medicine in India).",
    validationRules: "Max 50 characters.",
    normalizationRules: "Uppercase alphanumeric.",
    databaseField: "value",
    databaseTable: "PractitionerIdentifier",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.identifier[system='http://ndhm.gov.in/fhir/sid/imr-number'].value",
    fhirDatatype: "Identifier",
    systemUrl: "http://ndhm.gov.in/fhir/sid/imr-number",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "abdmHealthcareProfessionalId",
    uiLabel: "ABDM Healthcare Professional ID (HPID)",
    section: "Medical Registration",
    dataType: "string",
    required: false,
    repeatable: false,
    placeholder: "doctor@hpr.abdm",
    helpText: "Ayushman Bharat Digital Mission (ABDM) HPR ID.",
    validationRules: "Regex match ^[a-zA-Z0-9.\\-_]{4,30}@hpr\\.abdm$.",
    normalizationRules: "Lowercase.",
    databaseField: "value",
    databaseTable: "PractitionerIdentifier",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.identifier[system='https://hpr.abdm.gov.in/hpid'].value",
    fhirDatatype: "Identifier",
    systemUrl: "https://hpr.abdm.gov.in/hpid",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 4: Qualifications
  {
    name: "qualificationType",
    uiLabel: "Degree Category",
    section: "Qualifications",
    dataType: "enum",
    required: true,
    repeatable: true,
    allowedValues: ["UG", "PG", "SuperSpecialty", "Diploma", "Fellowship"],
    placeholder: "Select Category",
    helpText: "Select the classification of this degree.",
    validationRules: "Must be one of the enum values.",
    normalizationRules: "Upper case.",
    databaseField: "qualificationType",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.extension[url='http://drgodly.com/fhir/StructureDefinition/qualification-category']",
    fhirDatatype: "code",
    systemUrl: "http://drgodly.com/fhir/StructureDefinition/qualification-category",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "degreeName",
    uiLabel: "Degree / Certificate Title",
    section: "Qualifications",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., MBBS, MD, MS, DNB",
    helpText: "The formal title of the degree awarded.",
    validationRules: "String length between 2 and 50 characters.",
    normalizationRules: "Capitalize and trim whitespace.",
    databaseField: "code",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.code.text",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://terminology.hl7.org/CodeSystem/v2-0360",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "specialization",
    uiLabel: "Specialty / Subject",
    section: "Qualifications",
    dataType: "string",
    required: false,
    repeatable: true,
    placeholder: "e.g., Cardiology, General Surgery",
    helpText: "The core major or specialization field of this qualification.",
    validationRules: "Max 100 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "specialization",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.code.coding[system='http://snomed.info/sct'].display",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://snomed.info/sct",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "institution",
    uiLabel: "Institution / Medical School",
    section: "Qualifications",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., Grant Medical College, Mumbai",
    helpText: "Medical school or college attended to attain this degree.",
    validationRules: "String length between 2 and 150 characters.",
    normalizationRules: "Trim whitespace. Titlecase.",
    databaseField: "issuer",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.issuer.display",
    fhirDatatype: "Reference",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "issuingOrganization",
    uiLabel: "University / Board Name",
    section: "Qualifications",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., Maharashtra University of Health Sciences",
    helpText: "The university or board that certified and issued the degree.",
    validationRules: "Minimum 2 characters, max 150 characters.",
    normalizationRules: "Titlecase.",
    databaseField: "issuingOrganization",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.issuer.display",
    fhirDatatype: "Reference",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "country",
    uiLabel: "Country of Issue",
    section: "Qualifications",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "Select Country",
    helpText: "Country where this degree was issued.",
    validationRules: "Must be a valid 2-letter country code.",
    normalizationRules: "Uppercase.",
    databaseField: "country",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.extension[url='http://hl7.org/fhir/StructureDefinition/qualification-country']",
    fhirDatatype: "code",
    systemUrl: "urn:iso:std:iso:3166",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "completionDate",
    uiLabel: "Year / Date of Completion",
    section: "Qualifications",
    dataType: "date",
    required: true,
    repeatable: true,
    placeholder: "YYYY-MM-DD",
    helpText: "Date the degree was awarded.",
    validationRules: "Valid date. Must be in the past.",
    normalizationRules: "Date object.",
    databaseField: "periodEnd",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.period.end",
    fhirDatatype: "Period",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "certificateNumber",
    uiLabel: "Certificate Number",
    section: "Qualifications",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., CERT-77665",
    helpText: "Number printed on your degree certificate.",
    validationRules: "Min 2 characters, max 50 characters.",
    normalizationRules: "Uppercase alphanumeric.",
    databaseField: "certificateNumber",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.identifier.value",
    fhirDatatype: "Identifier",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "verificationStatus",
    uiLabel: "Verification Status",
    section: "Qualifications",
    dataType: "enum",
    required: true,
    repeatable: true,
    allowedValues: ["pending", "verified", "rejected"],
    databaseField: "verificationStatus",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.extension[url='http://drgodly.com/fhir/StructureDefinition/verification-status']",
    fhirDatatype: "code",
    systemUrl: "http://drgodly.com/fhir/StructureDefinition/verification-status",
    searchable: false,
    patientVisible: false,
    adminOnly: true,
    sensitive: false
  },
  {
    name: "documentReferenceId",
    uiLabel: "Qualification Document Link",
    section: "Qualifications",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "Select uploaded file",
    helpText: "Link to the PDF or image file containing the degree copy.",
    validationRules: "Must match a valid ID from the VerificationDocument table.",
    normalizationRules: "Trim whitespace.",
    databaseField: "documentReferenceId",
    databaseTable: "PractitionerQualification",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.qualification.extension[url='http://hl7.org/fhir/StructureDefinition/qualification-document'].value",
    fhirDatatype: "Reference",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 5: Specialty
  {
    name: "primarySpecialty",
    uiLabel: "Primary Specialty",
    section: "Specialty",
    dataType: "string",
    required: true,
    repeatable: false,
    placeholder: "Select Specialty",
    helpText: "Your primary specialty (mandatory for patient booking assignment).",
    validationRules: "Must match one of the predefined coded specialties list.",
    normalizationRules: "Coded ID storage.",
    databaseField: "specialties",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.specialty.coding[system='http://snomed.info/sct']",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://snomed.info/sct",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "secondarySpecialties",
    uiLabel: "Secondary Specialties",
    section: "Specialty",
    dataType: "array-string",
    required: false,
    repeatable: true,
    placeholder: "Select secondary specialties",
    helpText: "List secondary specialties or fellowships.",
    validationRules: "Array of valid SNOMED CT codes.",
    normalizationRules: "Array of codes.",
    databaseField: "specialties",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.specialty.coding",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://snomed.info/sct",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "areasOfExpertise",
    uiLabel: "Areas of Expertise",
    section: "Specialty",
    dataType: "array-string",
    required: false,
    repeatable: true,
    placeholder: "e.g., Obesity management, PCOS, metabolic health",
    helpText: "Enter specific keywords or topics you specialize in (useful for AI patient matchmaking).",
    validationRules: "String array. Maximum 10 items.",
    normalizationRules: "Trim, lowercase, strip special characters.",
    databaseField: "areasOfExpertise",
    databaseTable: "Practitioner",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.extension[url='http://drgodly.com/fhir/StructureDefinition/practitioner-expertise']",
    fhirDatatype: "string",
    systemUrl: "http://drgodly.com/fhir/StructureDefinition/practitioner-expertise",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 6: Professional Practice
  {
    name: "totalYearsOfExperience",
    uiLabel: "Years of Practice Experience",
    section: "Professional Practice",
    dataType: "number",
    required: true,
    repeatable: false,
    placeholder: "e.g., 10",
    helpText: "Total years since you finished your medical school residency.",
    validationRules: "Integer >= 0.",
    normalizationRules: "Parse string representation to integer.",
    databaseField: "yearsOfExperience",
    databaseTable: "Practitioner",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.extension[url='http://hl7.org/fhir/StructureDefinition/practitioner-experience-years']",
    fhirDatatype: "integer",
    systemUrl: "http://hl7.org/fhir/StructureDefinition/practitioner-experience-years",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "currentEmploymentStatus",
    uiLabel: "Employment Status",
    section: "Professional Practice",
    dataType: "enum",
    required: true,
    repeatable: false,
    allowedValues: ["full-time", "part-time", "contractor"],
    placeholder: "Select employment status",
    helpText: "Select your commitment model for DrGodly consultations.",
    validationRules: "Must match one of the allowed statuses.",
    normalizationRules: "Lowercase.",
    databaseField: "currentEmploymentStatus",
    databaseTable: "Practitioner",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.extension[url='http://drgodly.com/fhir/StructureDefinition/employment-status']",
    fhirDatatype: "code",
    systemUrl: "http://drgodly.com/fhir/StructureDefinition/employment-status",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "medicalIndemnityInsuranceNumber",
    uiLabel: "Medical Indemnity Insurance Number",
    section: "Professional Practice",
    dataType: "string",
    required: false,
    repeatable: false,
    placeholder: "e.g., POL-554433",
    helpText: "Your professional liability or indemnity policy identifier.",
    validationRules: "Max 100 characters.",
    normalizationRules: "Uppercase alphanumeric.",
    databaseField: "value",
    databaseTable: "PractitionerIdentifier",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.identifier[system='http://drgodly.com/fhir/sid/insurance'].value",
    fhirDatatype: "Identifier",
    systemUrl: "http://drgodly.com/fhir/sid/insurance",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: true
  },
  {
    name: "indemnityInsuranceExpiryDate",
    uiLabel: "Insurance Expiry Date",
    section: "Professional Practice",
    dataType: "date",
    required: false,
    repeatable: false,
    placeholder: "YYYY-MM-DD",
    helpText: "The expiry date of your active medical indemnity policy.",
    validationRules: "Must be in the future.",
    normalizationRules: "Date object.",
    databaseField: "indemnityInsuranceExpiryDate",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.identifier[system='http://drgodly.com/fhir/sid/insurance'].period.end",
    fhirDatatype: "Period",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 7: Organizations
  {
    name: "organizationName",
    uiLabel: "Affiliated Organization Name",
    section: "Organizations",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "Select or enter organization name",
    helpText: "Name of hospital, medical group, or clinic you work for.",
    validationRules: "String length between 2 and 150 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "name",
    databaseTable: "Organization",
    fhirResource: "Organization",
    fhirPath: "Organization.name",
    fhirDatatype: "string",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "organizationType",
    uiLabel: "Organization Type",
    section: "Organizations",
    dataType: "enum",
    required: true,
    repeatable: true,
    allowedValues: ["prov", "dept", "team", "govt", "ins"],
    placeholder: "Select type",
    helpText: "Classification of the organization entity.",
    validationRules: "Must be one of the pre-selected allowed values.",
    normalizationRules: "Lowercase.",
    databaseField: "type",
    databaseTable: "Organization",
    fhirResource: "Organization",
    fhirPath: "Organization.type",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://hl7.org/fhir/valueset/organization-type",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "designation",
    uiLabel: "Job Designation",
    section: "Organizations",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "Senior Consultant Physician",
    helpText: "Your official employment title/designation inside the organization.",
    validationRules: "String length between 2 and 100 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "designation",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.code.text",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://hl7.org/fhir/valueset/practitioner-role",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "department",
    uiLabel: "Department / Division",
    section: "Organizations",
    dataType: "string",
    required: false,
    repeatable: true,
    placeholder: "Outpatient Wellness Clinic",
    helpText: "Specific department you practice in at this organization.",
    validationRules: "Max 100 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "department",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.extension[url='http://drgodly.com/fhir/StructureDefinition/practitioner-role-department']",
    fhirDatatype: "string",
    systemUrl: "http://drgodly.com/fhir/StructureDefinition/practitioner-role-department",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "role",
    uiLabel: "Practitioner Role Function",
    section: "Organizations",
    dataType: "enum",
    required: true,
    repeatable: true,
    allowedValues: ["doctor", "nurse", "pharmacist", "therapist"],
    placeholder: "Select clinical role",
    helpText: "The clinical role you assume at this organization.",
    validationRules: "Must match one of the allowed role types.",
    normalizationRules: "Lowercase.",
    databaseField: "role",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.code.coding[system='http://terminology.hl7.org/CodeSystem/practitioner-role'].code",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://terminology.hl7.org/CodeSystem/practitioner-role",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "startDate",
    uiLabel: "Joining Date",
    section: "Organizations",
    dataType: "date",
    required: true,
    repeatable: true,
    placeholder: "YYYY-MM-DD",
    helpText: "Date you joined this organization.",
    validationRules: "Must be in the past.",
    normalizationRules: "Date object.",
    databaseField: "createdAt",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.period.start",
    fhirDatatype: "Period",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "endDate",
    uiLabel: "Leaving Date",
    section: "Organizations",
    dataType: "date",
    required: false,
    repeatable: true,
    placeholder: "YYYY-MM-DD",
    helpText: "Date you left this organization (leave blank if current affiliation).",
    validationRules: "Must be after startDate if provided.",
    normalizationRules: "Date object.",
    databaseField: "endDate",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.period.end",
    fhirDatatype: "Period",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "organizationIdentifier",
    uiLabel: "Organization Tax ID / PAN",
    section: "Organizations",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "Enter Tax ID",
    helpText: "Corporate identity number (e.g., EIN / PAN) of the organization.",
    validationRules: "Min 5 characters, max 30 characters.",
    normalizationRules: "Uppercase alphanumeric.",
    databaseField: "id",
    databaseTable: "Organization",
    fhirResource: "Organization",
    fhirPath: "Organization.identifier.value",
    fhirDatatype: "Identifier",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: true
  },
  {
    name: "organizationVerificationStatus",
    uiLabel: "Organization Verification Status",
    section: "Organizations",
    dataType: "enum",
    required: true,
    repeatable: true,
    allowedValues: ["pending", "verified", "failed"],
    databaseField: "active",
    databaseTable: "Organization",
    fhirResource: "Organization",
    fhirPath: "Organization.active",
    fhirDatatype: "boolean",
    searchable: false,
    patientVisible: false,
    adminOnly: true,
    sensitive: false
  },

  // SECTION 8: Locations
  {
    name: "locationName",
    uiLabel: "Location Name",
    section: "Locations",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., Apex Clinic Room 4",
    helpText: "Name of this specific physical clinic facility.",
    validationRules: "Minimum 2 characters, max 100 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "name",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.name",
    fhirDatatype: "string",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "addressLine1",
    uiLabel: "Address Line 1",
    section: "Locations",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., 123 Health Plaza Suite 200",
    helpText: "Primary street address (must not be home address).",
    validationRules: "String length between 5 and 150 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "address",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.address.line[0]",
    fhirDatatype: "Address",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "addressLine2",
    uiLabel: "Address Line 2",
    section: "Locations",
    dataType: "string",
    required: false,
    repeatable: true,
    placeholder: "e.g., Building B, 2nd Floor",
    helpText: "Apartment, suite, or building details.",
    validationRules: "Max 100 characters.",
    normalizationRules: "Trim whitespace.",
    databaseField: "address",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.address.line[1]",
    fhirDatatype: "Address",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "city",
    uiLabel: "City",
    section: "Locations",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., Bangalore",
    helpText: "City where the clinic is located.",
    validationRules: "Min 2 characters, max 100 characters.",
    normalizationRules: "Titlecase.",
    databaseField: "city",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.address.city",
    fhirDatatype: "Address",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "district",
    uiLabel: "District",
    section: "Locations",
    dataType: "string",
    required: false,
    repeatable: true,
    placeholder: "e.g., Bengaluru Urban",
    helpText: "District or county.",
    validationRules: "Max 100 characters.",
    normalizationRules: "Titlecase.",
    databaseField: "district",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.address.district",
    fhirDatatype: "Address",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "state",
    uiLabel: "State",
    section: "Locations",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., Karnataka",
    helpText: "State or province.",
    validationRules: "Minimum 2 characters, max 100 characters.",
    normalizationRules: "Capitalization.",
    databaseField: "state",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.address.state",
    fhirDatatype: "Address",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "postalCode",
    uiLabel: "Postal Code / ZIP Code",
    section: "Locations",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., 560001",
    helpText: "ZIP or Postal Code.",
    validationRules: "Must match standard postal code format for target country.",
    normalizationRules: "Uppercase, strip extra spaces.",
    databaseField: "postalCode",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.address.postalCode",
    fhirDatatype: "Address",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "country",
    uiLabel: "Country",
    section: "Locations",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "Select Country",
    helpText: "Country of the clinic location.",
    validationRules: "Must be a valid 2-letter country code.",
    normalizationRules: "Uppercase.",
    databaseField: "country",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.address.country",
    fhirDatatype: "Address",
    systemUrl: "urn:iso:std:iso:3166",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "latitude",
    uiLabel: "Latitude",
    section: "Locations",
    dataType: "number",
    required: false,
    repeatable: true,
    placeholder: "e.g., 12.9716",
    helpText: "Geographic coordinate latitude.",
    validationRules: "Valid float value between -90.0 and 90.0.",
    normalizationRules: "Convert string representation to float.",
    databaseField: "latitude",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.position.latitude",
    fhirDatatype: "decimal",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "longitude",
    uiLabel: "Longitude",
    section: "Locations",
    dataType: "number",
    required: false,
    repeatable: true,
    placeholder: "e.g., 77.5946",
    helpText: "Geographic coordinate longitude.",
    validationRules: "Float between -180.0 and 180.0.",
    normalizationRules: "Float conversion.",
    databaseField: "longitude",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.position.longitude",
    fhirDatatype: "decimal",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "locationType",
    uiLabel: "Location Type",
    section: "Locations",
    dataType: "enum",
    required: true,
    repeatable: true,
    allowedValues: ["clinic", "hosp", "pharm", "home"],
    placeholder: "Select location type",
    helpText: "Classification of the practice setting.",
    validationRules: "Must be one of the enum values.",
    normalizationRules: "Lowercase.",
    databaseField: "locationType",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.physicalType",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://terminology.hl7.org/CodeSystem/location-physical-type",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "virtualLocation",
    uiLabel: "Is Virtual Location?",
    section: "Locations",
    dataType: "boolean",
    required: true,
    repeatable: true,
    allowedValues: [],
    helpText: "Ticked if the location is simulated for digital telehealth consults.",
    validationRules: "Must be a boolean value.",
    normalizationRules: "Inferred database representation.",
    databaseField: "virtual",
    databaseTable: "Location",
    fhirResource: "Location",
    fhirPath: "Location.status",
    fhirDatatype: "code",
    systemUrl: "http://hl7.org/fhir/valueset/location-status",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 9: Languages
  {
    name: "languageCode",
    uiLabel: "Language ISO Code",
    section: "Languages",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., en",
    helpText: "Standard code representation.",
    validationRules: "Must be a valid 2-letter ISO code.",
    normalizationRules: "Lowercase.",
    databaseField: "languages",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.communication.language.coding.code",
    fhirDatatype: "CodeableConcept",
    systemUrl: "urn:ietf:bcp:47",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "languageName",
    uiLabel: "Language Name",
    section: "Languages",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., English, Hindi",
    helpText: "The language name.",
    validationRules: "Minimum 2 characters, max 50 characters.",
    normalizationRules: "Titlecase.",
    databaseField: "languages",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.communication.language.text",
    fhirDatatype: "CodeableConcept",
    systemUrl: "urn:ietf:bcp:47",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "proficiency",
    uiLabel: "Language Proficiency",
    section: "Languages",
    dataType: "enum",
    required: true,
    repeatable: true,
    allowedValues: ["native", "fluent", "intermediate", "basic"],
    placeholder: "Select proficiency",
    helpText: "Your level of speaking and writing ability in this language.",
    validationRules: "Must match one of the allowed proficiency values.",
    normalizationRules: "Lowercase.",
    databaseField: "proficiency",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.communication.extension[url='http://drgodly.com/fhir/StructureDefinition/language-proficiency']",
    fhirDatatype: "code",
    systemUrl: "http://drgodly.com/fhir/StructureDefinition/language-proficiency",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "preferredForConsultation",
    uiLabel: "Preferred for Patient Consultations",
    section: "Languages",
    dataType: "boolean",
    required: true,
    repeatable: true,
    helpText: "Check this if this language is your primary language for patient consultations.",
    validationRules: "Must be boolean.",
    normalizationRules: "Inferred.",
    databaseField: "preferredLanguage",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.communication.language.coding.extension[url='http://hl7.org/fhir/StructureDefinition/language-preference']",
    fhirDatatype: "boolean",
    systemUrl: "http://hl7.org/fhir/StructureDefinition/language-preference",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 10: Telemedicine Services
  {
    name: "videoConsultation",
    uiLabel: "Video Consultation",
    section: "Telemedicine Services",
    dataType: "boolean",
    required: true,
    repeatable: false,
    helpText: "Checked if you conduct live video consultation slots.",
    validationRules: "Boolean.",
    normalizationRules: "Inferred.",
    databaseField: "services",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.healthcareService",
    fhirDatatype: "Reference",
    systemUrl: "http://hl7.org/fhir/valueset/service-type",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "audioConsultation",
    uiLabel: "Audio Consultation",
    section: "Telemedicine Services",
    dataType: "boolean",
    required: true,
    repeatable: false,
    helpText: "Checked if you offer telephone/audio consultation slots.",
    validationRules: "Boolean.",
    normalizationRules: "Inferred.",
    databaseField: "services",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.healthcareService",
    fhirDatatype: "Reference",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "chatConsultation",
    uiLabel: "Text Chat Consultation",
    section: "Telemedicine Services",
    dataType: "boolean",
    required: true,
    repeatable: false,
    helpText: "Checked if you consult via text chat messaging.",
    validationRules: "Boolean.",
    normalizationRules: "Inferred.",
    databaseField: "services",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.healthcareService",
    fhirDatatype: "Reference",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "followUpConsultation",
    uiLabel: "Follow-up Reviews",
    section: "Telemedicine Services",
    dataType: "boolean",
    required: true,
    repeatable: false,
    helpText: "Checked if you conduct follow-up consultations.",
    validationRules: "Boolean.",
    normalizationRules: "Inferred.",
    databaseField: "services",
    databaseTable: "PractitionerRole",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.healthcareService",
    fhirDatatype: "Reference",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 11: Pricing
  {
    name: "initialConsultationFee",
    uiLabel: "Initial Consultation Fee",
    section: "Pricing",
    dataType: "number",
    required: true,
    repeatable: false,
    placeholder: "500.00",
    helpText: "Fee for the first evaluation consultation session.",
    validationRules: "Must be greater than or equal to 0.",
    normalizationRules: "Float conversion.",
    databaseField: "initialFee",
    databaseTable: "Practitioner",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "followUpConsultationFee",
    uiLabel: "Follow-up Consultation Fee",
    section: "Pricing",
    dataType: "number",
    required: true,
    repeatable: false,
    placeholder: "300.00",
    helpText: "Fee charged for standard follow-up reviews.",
    validationRules: "Must be >= 0.",
    normalizationRules: "Float conversion.",
    databaseField: "followUpFee",
    databaseTable: "Practitioner",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "secondOpinionFee",
    uiLabel: "Second Opinion Review Fee",
    section: "Pricing",
    dataType: "number",
    required: true,
    repeatable: false,
    placeholder: "1000.00",
    helpText: "Fee for complex document reviews and second opinions.",
    validationRules: "Must be >= 0.",
    normalizationRules: "Float conversion.",
    databaseField: "secondOpinionFee",
    databaseTable: "Practitioner",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "currency",
    uiLabel: "Currency",
    section: "Pricing",
    dataType: "enum",
    required: true,
    repeatable: false,
    allowedValues: ["INR", "USD", "GBP", "EUR"],
    placeholder: "Select Currency",
    helpText: "Currency used for pricing.",
    validationRules: "Must match one of the allowed currencies.",
    normalizationRules: "Uppercase.",
    databaseField: "currency",
    databaseTable: "Practitioner",
    systemUrl: "urn:iso:std:iso:4217",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 12: Availability
  {
    name: "dayOfWeek",
    uiLabel: "Day of Week",
    section: "Availability",
    dataType: "enum",
    required: true,
    repeatable: true,
    allowedValues: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"],
    placeholder: "Select Day",
    helpText: "The day of the week this slot applies to.",
    validationRules: "Must be one of the seven days.",
    normalizationRules: "Uppercase.",
    databaseField: "dayOfWeek",
    databaseTable: "PractitionerAvailability",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.availableTime.daysOfWeek",
    fhirDatatype: "code",
    systemUrl: "http://hl7.org/fhir/valueset/days-of-week",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "startTime",
    uiLabel: "Start Time",
    section: "Availability",
    dataType: "time",
    required: true,
    repeatable: true,
    placeholder: "09:00",
    helpText: "Time the availability period starts.",
    validationRules: "Regex match ^([0-1]\\d|2[0-3]):[0-5]\\d$.",
    normalizationRules: "Ensure 24h formatting.",
    databaseField: "availableFrom",
    databaseTable: "PractitionerAvailability",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.availableTime.availableStartTime",
    fhirDatatype: "time",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "endTime",
    uiLabel: "End Time",
    section: "Availability",
    dataType: "time",
    required: true,
    repeatable: true,
    placeholder: "17:00",
    helpText: "Time the availability period ends.",
    validationRules: "Must be chronologically after startTime. Must match ^([0-1]\\d|2[0-3]):[0-5]\\d$.",
    normalizationRules: "24h format.",
    databaseField: "availableTo",
    databaseTable: "PractitionerAvailability",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.availableTime.availableEndTime",
    fhirDatatype: "time",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "timezone",
    uiLabel: "Timezone",
    section: "Availability",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "e.g., Asia/Kolkata",
    helpText: "Select your active timezone.",
    validationRules: "Must be a valid IANA timezone string.",
    normalizationRules: "Default to 'Asia/Kolkata' if in India, but do not hardcode in Prisma column default.",
    databaseField: "timezone",
    databaseTable: "PractitionerAvailability",
    fhirResource: "PractitionerRole",
    fhirPath: "PractitionerRole.availableTime.extension[url='http://hl7.org/fhir/StructureDefinition/timezone']",
    fhirDatatype: "string",
    systemUrl: "http://hl7.org/fhir/StructureDefinition/timezone",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "appointmentDurationMinutes",
    uiLabel: "Consultation Session Duration",
    section: "Availability",
    dataType: "number",
    required: true,
    repeatable: true,
    placeholder: "15",
    helpText: "Duration of each appointment slot in minutes.",
    validationRules: "Positive integer between 5 and 120.",
    normalizationRules: "Parse string to integer.",
    databaseField: "duration",
    databaseTable: "PractitionerAvailability",
    searchable: false,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 13: Professional Profile
  {
    name: "professionalBio",
    uiLabel: "Professional Biography",
    section: "Professional Profile",
    dataType: "string",
    required: true,
    repeatable: false,
    placeholder: "Write a brief overview of your clinical experience...",
    helpText: "This biography is displayed on your public profile page for patients to read.",
    validationRules: "String length between 50 and 2000 characters.",
    normalizationRules: "Clean HTML tags, trim whitespace.",
    databaseField: "bio",
    databaseTable: "Practitioner",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 14: Verification Documents
  {
    name: "documentType",
    uiLabel: "Document Type",
    section: "Verification Documents",
    dataType: "enum",
    required: true,
    repeatable: true,
    allowedValues: ["license", "qualification", "identity"],
    placeholder: "Select Document Type",
    helpText: "The category classification of the uploaded file.",
    validationRules: "Must match one of the allowed document types.",
    normalizationRules: "Lowercase.",
    databaseField: "docType",
    databaseTable: "VerificationDocument",
    fhirResource: "DocumentReference",
    fhirPath: "DocumentReference.type.text",
    fhirDatatype: "CodeableConcept",
    systemUrl: "http://loinc.org",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },
  {
    name: "fileId",
    uiLabel: "File Storage Reference",
    section: "Verification Documents",
    dataType: "string",
    required: true,
    repeatable: true,
    placeholder: "Upload File...",
    helpText: "Local file path reference.",
    validationRules: "Must be a valid URL/URI string.",
    normalizationRules: "Trim whitespace.",
    databaseField: "url",
    databaseTable: "VerificationDocument",
    fhirResource: "DocumentReference",
    fhirPath: "DocumentReference.content.attachment.url",
    fhirDatatype: "url",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: true
  },

  // SECTION 15: Consent and Agreements
  {
    name: "platformTermsAccepted",
    uiLabel: "Accept Platform Terms of Service",
    section: "Consent and Agreements",
    dataType: "boolean",
    required: true,
    repeatable: false,
    helpText: "Explicit acceptance of the general platform Terms of Service.",
    validationRules: "Must be true.",
    databaseField: "platformTermsAccepted",
    databaseTable: "Practitioner",
    fhirResource: "Consent",
    fhirPath: "Consent.provision.type",
    fhirDatatype: "code",
    systemUrl: "http://hl7.org/fhir/valueset/consent-provision-type",
    searchable: false,
    patientVisible: false,
    adminOnly: false,
    sensitive: false
  },

  // SECTION 16: Onboarding Status
  {
    name: "status",
    uiLabel: "Application Status",
    section: "Onboarding Status",
    dataType: "enum",
    required: true,
    repeatable: false,
    allowedValues: ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "CHANGES_REQUESTED", "VERIFIED", "REJECTED", "SUSPENDED"],
    databaseField: "status",
    databaseTable: "Practitioner",
    fhirResource: "Practitioner",
    fhirPath: "Practitioner.active",
    fhirDatatype: "boolean",
    searchable: true,
    patientVisible: true,
    adminOnly: false,
    sensitive: false
  }
];
